### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/doomsday-resources#2]
Should contain:

- app title
- one-sentence description
- development instructions (how to go from 0 to running in dev)

**Comment by JolliestJames** [comment]
6876ba4914d9b03f45489003894a9792246244a4 and 787875cddf5632a6e7c2d3597976e906f8e6df2a reference this

**Comment by JolliestJames** [comment]
f44f2c5ad25fadb417b3f926ccd5639dc668d05a refs this
